//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibGeCv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competenze
    {
        public int IdCs { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Livello { get; set; }
        public Nullable<int> IdCv { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
    }
}
