//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibGeCv
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspLav
    {
        public int IdEl { get; set; }
        public Nullable<int> AnnoI { get; set; }
        public Nullable<int> AnnoF { get; set; }
        public string Qualifica { get; set; }
        public string Descrizione { get; set; }
        public Nullable<int> IdCv { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
    }
}
